all: basic  config  full

basic:
	make -C sched_basic

config:
	make -C sched_config

full:
	make -C sched_full

clean:
	make -C sched_basic clean
	make -C sched_config clean
	make -C sched_full clean

