all: sched_basic sched_config sched_full 

sched_basic:
	make -C sched_basic

sched_config:
	make -C sched_config

sched_full:
	make -C sched_full

clean:
	make -C sched_basic clean
	make -C sched_config clean
	make -C sched_full clean

