all: bs perf pth sche

bs:
	make -C basic

perf:
	make -C performance

pth:
	make -C pthread

sche:
	make -C sched

clean:
	make -C basic clean
	make -C performance clean
	make -C pthread clean
	make -C sched clean
