all:qth mth arg pth

arg:
	make -C argobots

mth:
	make -C massivethreads

qth:
	make -C qthreads

pth:
	make -C pthreads

clean:
	make -C argobots clean
	make -C massivethreads clean
	make -C qthreads clean
	make -C pthreads clean
